apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
  - image: my-web-app
    imagePullPolicy: Never
    name: nodewebapp
    ports:
    - containerPort: 3000
