version: '3'
services:
  web:
    image: my-web-app
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped